# Generated by Django 2.2.7 on 2019-11-07 14:25

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
        migrations.AlterModelTable(
            name='photo',
            table='photo',
        ),
    ]
