# Generated by Django 2.2.7 on 2019-11-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20191107_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='uploader',
            new_name='creator',
        ),
    ]
