# Generated by Django 2.2.7 on 2019-11-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20191109_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
