# Generated by Django 2.2.7 on 2019-11-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20191112_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
