# Generated by Django 2.2.7 on 2019-11-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20191113_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='total_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
